name: Releases app

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # push event match the regex v* i.e. v1.0, v1.0.1    

env: 
  PROJECT_PATH: ScanTextImage/ScanTextImage.csproj

jobs:
  deploy:
    name: deploy WPF app
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name : Setup dotnet
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 3.1.x

      - name: Restore project
        run: dotnet restore ${{env.PROJECT_PATH}}

      - name: Build project
        run: dotnet run build ${{env.PROJECT_PATH}} -c Release --no-restore

      - name: Publish project
        run: dotnet publish ${{env.PROJECT_PATH}} -c Release --self-contained false --no-build
          
      # - name: Create release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, do not need to create own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: TODO
      #     draft: true
      #     prerelease: false
