name: Releases app

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # push event match the regex v* i.e. v1.0, v1.0.1    

env: 
  PROJECT_PATH: ScanTextImage/ScanTextImage.csproj

jobs:
  deploy:
    name: deploy WPF app
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name : Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'
        
      - name: Restore, build and publish project
        run: |
          dotnet restore ${{env.PROJECT_PATH}}
          dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore
          dotnet publish ${{env.PROJECT_PATH}} -c Release --self-contained false --no-build

      - name: zip folder
        run: Compress-Archive -Path ScanTextImage/bin/Release/net8.0-windows/publish/* -Destination ScanTextFromImage.zip

      - name: test
        run: dir -s
      
      # - name: Create release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, do not need to create own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: TODO
      #     draft: true
      #     prerelease: false
      
      # - name: Upload release assert
      #   uses: csexton/release-asset-action@v3
      #   with:
      #     pattern: ScanTextImage/bin/Release/net8.0-windows/publish/*/exe
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     release-url: ${{ steps.create_release.outputs.upload_url }}
